import { existsSync, mkdirSync, writeFileSync, chmodSync, readFileSync } from 'fs'
import { join, resolve } from 'path'
import { homedir } from 'os'
import { app } from 'electron'

const CLI_DIR = join(homedir(), '.local', 'bin')
const CLI_PATH = join(CLI_DIR, 'multiterm')

// Bump this constant whenever the shell launcher script changes in a way that
// requires re-installation. On startup, if the installed file does not contain
// the matching marker, the file is force-overwritten.
const SCHEMA_VERSION = 2
const SCHEMA_MARKER = `# multiterm-installer-schema=${SCHEMA_VERSION}`

/**
 * Returns the absolute path to the bundled CLI entry CJS file.
 *
 * - Packaged: inside the .app bundle's Resources/app.asar (or extraResources)
 * - Dev: `{repo}/out/main/cli-entry.js` produced by `npm run build:main`
 */
function resolveCliBundlePath(): string {
  if (app.isPackaged) {
    // electron-builder copies extra resources next to app.asar under Resources/
    return join(process.resourcesPath, 'cli-entry.js')
  }
  // Development build — electron-vite outputs to out/main/
  return resolve(__dirname, '..', 'main', 'cli-entry.js')
}

function buildScript(cliBundlePath: string): string {
  return `#!/bin/sh
${SCHEMA_MARKER}
# multiterm launcher — execs the bundled CLI from the installed app.
# Do not edit: this file is auto-generated by Multiterm Studio on startup.

NODE_BIN="\${MULTITERM_NODE:-node}"
CLI_BUNDLE="${cliBundlePath}"
exec "$NODE_BIN" "$CLI_BUNDLE" "$@"
`
}

/**
 * Returns true if the installed file is current (contains the schema marker).
 * Returns false if the file is missing or has an older schema version.
 */
function isCurrentSchema(): boolean {
  if (!existsSync(CLI_PATH)) return false
  try {
    const content = readFileSync(CLI_PATH, 'utf-8')
    return content.includes(SCHEMA_MARKER)
  } catch {
    return false
  }
}

export function installCli(): void {
  try {
    if (process.platform !== 'darwin') return

    // Skip installation when the current schema is already present.
    if (isCurrentSchema()) return

    const cliBundlePath = resolveCliBundlePath()
    const script = buildScript(cliBundlePath)

    mkdirSync(CLI_DIR, { recursive: true })
    writeFileSync(CLI_PATH, script, 'utf-8')
    chmodSync(CLI_PATH, 0o755)

    const pathEnv = process.env.PATH ?? ''
    if (!pathEnv.includes('.local/bin')) {
      console.log(
        '[cli-installer] multiterm installed at ~/.local/bin/multiterm. ' +
          'Add ~/.local/bin to your PATH if not already present.'
      )
    }
  } catch {
    // Silent failure — CLI install is best-effort
  }
}
