import { mkdirSync, writeFileSync, existsSync } from 'fs'
import { join } from 'path'
import { homedir } from 'os'

// The OSC 7 escape sequence notifies the terminal of the current working directory.
// Format: \e]7;file://<host><absolute-path>\a
const OSC7_EMIT = `printf '\\e]7;file://%s%s\\a' "$(hostname)" "$PWD"`

// The function name and env marker use the _MTS_ namespace to avoid collisions.
const HOOK_FN = '__mts_osc7'
const ZDOTDIR_MARKER = '_MTS_ZDOTDIR'

function buildOsc7Function(): string {
  return `${HOOK_FN}() { ${OSC7_EMIT}; }`
}

/**
 * Returns a one-line shell snippet to inject into the PTY after spawn,
 * or null if the shell handles OSC 7 natively (fish) or is unrecognised.
 *
 * The snippet ends with `clear` so the injected setup does not pollute the
 * user's visible scroll history.
 */
export function osc7ShellHook(shell: string): string | null {
  const base = shell.split('/').pop() ?? shell

  if (base === 'zsh') {
    const fn = buildOsc7Function()
    return `${fn}; precmd_functions+=(${HOOK_FN}); clear`
  }

  if (base === 'bash' || base === 'sh') {
    const fn = buildOsc7Function()
    // Preserve any existing PROMPT_COMMAND while prepending our hook.
    return `${fn}; ` + `PROMPT_COMMAND="${HOOK_FN}; \${PROMPT_COMMAND:-}"; ` + `clear`
  }

  // fish emits OSC 7 natively — no injection needed.
  return null
}

/**
 * Builds (or reuses) a zsh integration directory under `baseDir` that contains
 * a `.zshrc` which:
 *   1. Restores the real ZDOTDIR from the `_MTS_ZDOTDIR` env var.
 *   2. Sources the user's real `.zshrc` if `realZdotdir` is provided.
 *   3. Defines `__mts_osc7` and appends it to `precmd_functions`.
 *
 * Returns the path to the integration directory. The caller should set
 * `ZDOTDIR` to this path and `_MTS_ZDOTDIR` to `realZdotdir` (or empty)
 * before spawning zsh.
 *
 * Passing `baseDir` (default: `~/.multiterm-studio/zsh-integration`) allows
 * tests to redirect writes to a temp directory.
 */
export function zshIntegrationDir(
  realZdotdir: string | undefined,
  baseDir: string = join(homedir(), '.multiterm-studio', 'zsh-integration')
): string {
  const dir = baseDir
  const zshrcPath = join(dir, '.zshrc')

  if (existsSync(zshrcPath)) {
    return dir
  }

  mkdirSync(dir, { recursive: true })

  const fn = buildOsc7Function()
  const sourceUserRc = realZdotdir
    ? `[[ -f "${realZdotdir}/.zshrc" ]] && source "${realZdotdir}/.zshrc"`
    : ''

  const zshrc = [
    '# Generated by Multiterm Studio — do not edit manually.',
    '',
    '# 1. Restore the real ZDOTDIR so sub-shells find the user config.',
    `ZDOTDIR="\${${ZDOTDIR_MARKER}:-}"`,
    '',
    '# 2. Source the user real .zshrc if available.',
    sourceUserRc,
    '',
    '# 3. Register the OSC 7 hook.',
    fn + ';',
    `precmd_functions+=(${HOOK_FN})`
  ]
    .filter((line) => line !== undefined)
    .join('\n')

  writeFileSync(zshrcPath, zshrc + '\n', { encoding: 'utf8' })

  return dir
}
